
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ir.ac.guilan.Compiler.Project.Cola.syntactic;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EntryPoint = 30;
  public static final int Else = 29;
  public static final int RPar = 21;
  public static final int ForLoop = 4;
  public static final int Colon = 14;
  public static final int Semi = 9;
  public static final int Begin = 24;
  public static final int Var = 32;
  public static final int LPar = 20;
  public static final int Assign = 16;
  public static final int RBracelet = 13;
  public static final int Comma = 15;
  public static final int EndBlock = 11;
  public static final int True = 26;
  public static final int LBracelet = 12;
  public static final int StringConst = 31;
  public static final int PlusPlus = 22;
  public static final int BeginBlock = 10;
  public static final int False = 27;
  public static final int MinusMinus = 23;
  public static final int Operator = 17;
  public static final int Type = 33;
  public static final int End = 25;
  public static final int In = 5;
  public static final int Identifier = 8;
  public static final int EOF = 0;
  public static final int Comparator = 18;
  public static final int MemDef = 3;
  public static final int NumValue = 34;
  public static final int If = 7;
  public static final int Return = 6;
  public static final int error = 1;
  public static final int While = 28;
  public static final int Dot = 19;
  public static final int TypeDef = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TypeDef",
  "MemDef",
  "ForLoop",
  "In",
  "Return",
  "If",
  "Identifier",
  "Semi",
  "BeginBlock",
  "EndBlock",
  "LBracelet",
  "RBracelet",
  "Colon",
  "Comma",
  "Assign",
  "Operator",
  "Comparator",
  "Dot",
  "LPar",
  "RPar",
  "PlusPlus",
  "MinusMinus",
  "Begin",
  "End",
  "True",
  "False",
  "While",
  "Else",
  "EntryPoint",
  "StringConst",
  "Var",
  "Type",
  "NumValue"
  };
}

